//! Stable identifiers.
//!
//! All ids are fixed-size byte arrays and are displayed as base58, matching the
//! convention Freenet itself uses for contract keys.

use core::fmt;

use serde::{Deserialize, Serialize};

macro_rules! byte_id {
    (
        $(#[$attr:meta])*
        $name:ident($len:literal)
    ) => {
        $(#[$attr])*
        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
        pub struct $name(pub [u8; $len]);

        impl $name {
            pub const LEN: usize = $len;

            pub const fn from_bytes(bytes: [u8; $len]) -> Self {
                Self(bytes)
            }

            pub fn as_bytes(&self) -> &[u8; $len] {
                &self.0
            }

            pub fn to_base58(&self) -> String {
                bs58::encode(&self.0).into_string()
            }

            pub fn from_base58(s: &str) -> Option<Self> {
                let mut out = [0u8; $len];
                let written = bs58::decode(s).onto(&mut out).ok()?;
                if written == $len {
                    Some(Self(out))
                } else {
                    None
                }
            }

            /// Truncated form for dense UI (avatars, task chips, log lines).
            pub fn short(&self) -> String {
                self.to_base58().chars().take(8).collect()
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.to_base58())
            }
        }

        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}({})", stringify!($name), self.short())
            }
        }
    };
}

byte_id! {
    /// A member's identity: the raw bytes of their ed25519 public key.
    ///
    /// Identity on Freenet is a keypair, not an account on a server, so the
    /// public key *is* the user id. Every write to a board is signed by one of
    /// these and the contract verifies it.
    MemberId(32)
}

byte_id! {
    /// Content hash of an [`crate::envelope::Envelope`]; the key ops are stored under.
    ///
    /// Content addressing is what makes re-sending an op free: a duplicate lands
    /// on the same key and the union is unchanged.
    OpId(32)
}

byte_id! {
    /// Identifies a task for the life of the board. Randomly generated by the
    /// client that creates the task.
    TaskId(16)
}

byte_id! {
    /// Identifies a column. Random rather than derived from the title so that
    /// renaming a column does not orphan the tasks sitting in it.
    ColumnId(16)
}

byte_id! {
    /// A task contract's instance id — a task's address, and the whole of a link
    /// to it.
    ///
    /// Unlike [`TaskId`], which was only ever unique within one board, this is
    /// globally resolvable: it is what you fetch. A pasted link needs nothing
    /// beside it, which matters because Freenet has no reverse index to look a
    /// task up in.
    TaskAddr(32)
}

byte_id! {
    /// Content hash of a registry listing.
    ListingId(32)
}

byte_id! {
    /// An organization contract's instance id.
    OrgId(32)
}

byte_id! {
    /// A board contract's instance id, as the registry records it.
    ///
    /// Kept as a plain 32-byte id rather than Freenet's `ContractInstanceId` so
    /// that `pj-core` stays free of any Freenet dependency and still compiles into
    /// the contract, the frontend, and native tests alike.
    BoardId(32)
}
